### ISSUE TITLE
Surveillance 

### ISSUE THREAD

**Issue by debatik** [Debatikcenter/debatikcenter#14] opened 2018-03-13 16:32 UTC
We are working for the Surveillance photo . For the moment is fine like this. If you have ideas please suggest.

**Comment by rskikuli** [comment] 2018-03-13 20:31
this is a duplicate of this issue https://github.com/Debatikcenter/debatikcenter/issues/4, closing this.

**Closed as completed by rskikuli** 2018-03-13 20:31 UTC
Labels: duplicate
